Display MiB instead of bytes when downloading base firmware
X1Plus/X1Plus pull request #104
Opened 2024-03-19 14:18 UTC by EfogDev

Because cmon, bytes :)

2024-03-19 16:47 UTC, balika011 requested changes

2024-03-20 08:17 UTC, EfogDev commented on installer/install.py
> +                    report_interim_progress(f"Downloading... ({curlen_mib} / {totlen_mib} MiB)")
@balika011 ok its up to you however men in black would surely be cooler

2024-03-22 05:26 UTC, jwise commented
The reason this is taking forever to get merged is that none of us actually ever run `kexec_ui` all that often.  I didn't test it but I'll take the blame if it doesn't work.  r+ me.

2024-03-22 05:29 UTC, jwise commented
ramboing this in despite CI failing because CI necessarily fails on forks because of the annoying key crypto thing

2024-03-22 05:30 UTC, merged

2024-03-22 07:42 UTC, singingtelegram commented
Why was it changed from MiB to MB? In a Linux environment MiB is more common and if MB is used it should be multiples of 1000